version: '3'

services:

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Istanbul
      - MAILDEV_WEB_PORT=80
      - MAILDEV_SMTP_PORT=25
    # - MAILDEV_OUTGOING_HOST=10.10.10.10
    # - MAILDEV_OUTGOING_PORT=25
    # - MAILDEV_OUTGOING_USER=hilmi
    # - MAILDEV_OUTGOING_PASS=12345
    # - MAILDEV_OUTGOING_SECURE
    # - MAILDEV_WEB_USER=hilmi
    # - MAILDEV_WEB_PASS=12345
    ports:
      - "80:80"
      - "25:25"
